<?php

return [
    'panel' => [
        'body' => [
            'bg' => '#eaf1f7',
            'text' => '#0f172a',
        ],
        'topbar' => [
            'bg' => '#f8fbfe',
            'border' => '#9fb6d1',
            'text' => '#0f172a',
            'muted_text' => '#52667d',
            'toggle_border' => '#8fa8c3',
            'toggle_bg' => '#ecf3f9',
            'toggle_text' => '#334155',
            'toggle_hover_bg' => '#d7e3f0',
        ],
        'sidebar' => [
            'bg' => '#8fa8c3',
            'text' => '#122033',
            'icon' => '#1f334d',
            'border' => '#7a99bd',
            'hover_bg' => '#a3bad3',
            'active_bg' => '#b0c4de',
            'active_text' => '#0f172a',
            'active_icon' => '#0f172a',
            'inactive_icon' => '#2f4765',
        ],
        'table' => [
            'surface' => '#ffffff',
            'surface_muted' => '#ecf3f9',
            'surface_soft' => '#b0c4de',
            'heading_text' => '#0f172a',
            'head_text' => '#0f172a',
            'muted_text' => '#52667d',
            'body_text' => '#334155',
            'placeholder_text' => '#70859a',
            'container_border' => '#8fa8c3',
            'section_border' => '#9fb6d1',
            'grid_border' => '#8fa8c3',
            'control_border' => '#c3d4e7',
            'input_bg' => '#f8fbfe',
            'input_focus_border' => '#7a99bd',
            'row_hover' => '#c3d4e7',
            'row_selected' => '#d7e3f0',
            'pagination_active_bg' => '#b0c4de',
            'pagination_active_border' => '#8fa8c3',
            'pagination_active_text' => '#0f172a',
            'row_even' => '#d7e3f0',
            'row_odd' => '#ffffff',
        ],
        'form' => [
            'label_text' => '#334155',
            'text' => '#0f172a',
            'placeholder_text' => '#70859a',
            'bg' => '#ffffff',
            'border' => '#8fa8c3',
            'focus_border' => '#7a99bd',
            'focus_ring' => '#c3d4e7',
            'checkbox_border' => '#7a99bd',
            'checkbox_bg' => '#ffffff',
            'checkbox_checked' => '#8fa8c3',
            'checkbox_focus_ring' => '#c3d4e7',
        ],
        'status' => [
            'success_bg' => '#d7e3f0',
            'success_text' => '#28415f',
            'warning_bg' => '#ecf3f9',
            'warning_text' => '#52667d',
            'neutral_bg' => '#dbe7f3',
            'neutral_text' => '#475569',
            'danger_bg' => '#c3d4e7',
            'danger_text' => '#223753',
        ],
        'button' => [
            'primary_bg' => '#8fa8c3',
            'primary_hover_bg' => '#7a99bd',
            'primary_text' => '#ffffff',
            'soft_bg' => '#ecf3f9',
            'soft_border' => '#9fb6d1',
            'soft_text' => '#334155',
            'soft_hover_bg' => '#d7e3f0',
            'toggle_active_bg' => '#8fa8c3',
            'toggle_active_hover_bg' => '#7a99bd',
            'toggle_inactive_bg' => '#b0c4de',
            'toggle_inactive_hover_bg' => '#9fb6d1',
            'toggle_text' => '#ffffff',
            'danger_bg' => '#d7e3f0',
            'danger_hover_bg' => '#c3d4e7',
            'danger_border' => '#9fb6d1',
            'danger_text' => '#223753',
        ],
        'scrollbar' => [
            'track' => '#ecf3f9',
            'thumb' => '#8fa8c3',
            'thumb_hover' => '#7a99bd',
        ],
    ],
];
