<?php

return [
    'panel' => [
        'body' => [
            'bg' => '#f1f5f9',
            'text' => '#0f172a',
        ],
        'topbar' => [
            'bg' => '#ffffff',
            'border' => '#e2e8f0',
            'text' => '#0f172a',
            'muted_text' => '#475569',
            'toggle_border' => '#cbd5e1',
            'toggle_bg' => '#ffffff',
            'toggle_text' => '#334155',
            'toggle_hover_bg' => '#f1f5f9',
        ],
        'sidebar' => [
            'bg' => '#8b1c1c',
            'text' => '#fef2f2',
            'icon' => '#fecaca',
            'border' => '#991b1b',
            'hover_bg' => '#991b1b',
            'active_bg' => '#ff0000',
            'active_text' => '#ffffff',
            'active_icon' => '#ffffff',
            'inactive_icon' => '#fecaca',
        ],
        'table' => [
            'surface' => '#ffffff',
            'surface_muted' => '#f8fafc',
            'surface_soft' => '#8b1c1c',
            'heading_text' => '#0f172a',
            'head_text' => '#FFF',
            'muted_text' => '#64748b',
            'body_text' => '#334155',
            'placeholder_text' => '#94a3b8',
            'container_border' => '#e2e8f0',
            'section_border' => '#e2e8f0',
            'grid_border' => '#000',
            'control_border' => '#dbeafe',
            'input_bg' => '#f8fbff',
            'input_focus_border' => '#60a5fa',
            'row_hover' => '#fef3c7',
            'row_selected' => '#eff6ff',
            'pagination_active_bg' => '#fde68a',
            'pagination_active_border' => '#fcd34d',
            'pagination_active_text' => '#0f172a',
        ],
        'form' => [
            'label_text' => '#334155',
            'text' => '#0f172a',
            'placeholder_text' => '#94a3b8',
            'bg' => '#ffffff',
            'border' => '#8b1c1c',
            'focus_border' => '#8b1c1c',
            'focus_ring' => '#8b1c1c',
            'checkbox_border' => '#8b1c1c',
            'checkbox_bg' => '#8b1c1c',
            'checkbox_checked' => '#8b1c1c',
            'checkbox_focus_ring' => '#8b1c1c',
        ],
        'status' => [
            'success_bg' => '#d1fae5',
            'success_text' => '#047857',
            'warning_bg' => '#fef3c7',
            'warning_text' => '#b45309',
            'neutral_bg' => '#e2e8f0',
            'neutral_text' => '#475569',
            'danger_bg' => '#ffe4e6',
            'danger_text' => '#be123c',
        ],
        'button' => [
            'primary_bg' => '#0f172a',
            'primary_hover_bg' => '#1e293b',
            'primary_text' => '#ffffff',
            'soft_bg' => '#f8fbff',
            'soft_border' => '#dbeafe',
            'soft_text' => '#334155',
            'soft_hover_bg' => '#ffffff',
            'toggle_active_bg' => '#475569',
            'toggle_active_hover_bg' => '#334155',
            'toggle_inactive_bg' => '#059669',
            'toggle_inactive_hover_bg' => '#047857',
            'toggle_text' => '#ffffff',
            'danger_bg' => '#fff1f2',
            'danger_hover_bg' => '#ffe4e6',
            'danger_border' => '#fecdd3',
            'danger_text' => '#be123c',
        ],
    ],
];
